spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
---
spring:
  profiles: docker

  datasource:
    url: jdbc:postgresql://db-bot:5432/postgres